// codegeneration at: 13.09.2016 16:12:32
// ------------------------------------------------------------------------------
// <auto-generated>
//       This file has been generated by the tool: PSBuilder
//       Version:[1.0.15.3941]
// </auto-generated>
// ------------------------------------------------------------------------------

// START: Significant code

// Start of usercode. ID: UserCodeSection

// End of usercode.

namespace FP.NavigatorWeb.Common.Initialization
{
	/// <summary>
	/// contains information about software supported by the meter
	/// </summary>
	export class SupportedSoftwareInfo
	{ 
		//#region t4 generated members 
		private m_Software: FP.NavigatorWeb.Common.Number16Bit;

		private m_ExpirationDate: FP.NavigatorWeb.Common.FPDate;

		//#endregion

		//#region t4 generated properties 
		/// <summary>
        /// Gets or sets the Software.
		/// Description: the type of software supported (Navigator, NavigatorPlus, Mailone)
        /// </summary>
        /// <value>The Software.</value>
		get Software(): FP.NavigatorWeb.Common.Number16Bit { return this.m_Software; }
		set Software(value: FP.NavigatorWeb.Common.Number16Bit) { this.m_Software = value; }

		/// <summary>
        /// Gets or sets the ExpirationDate.
		/// Description: Expiration date of this software (for time limited versions or demo versions)
        /// </summary>
        /// <value>The ExpirationDate.</value>
		get ExpirationDate(): FP.NavigatorWeb.Common.FPDate { return this.m_ExpirationDate; }
		set ExpirationDate(value: FP.NavigatorWeb.Common.FPDate) { this.m_ExpirationDate = value; }

		//#endregion
	}
}

// END: Significant code