// codegeneration at: 13.09.2016 15:24:48
// ------------------------------------------------------------------------------
// <auto-generated>
//       This file has been generated by the tool: PSBuilder
//       Version:[1.0.15.3941]
// </auto-generated>
// ------------------------------------------------------------------------------

// START: Significant code

// Start of usercode. ID: UserCodeSection

// End of usercode.

namespace FP.NavigatorWeb.Common.Printing
{
	/// <summary>
	/// 
	/// </summary>
	export class BzlItemInfo
	{ 
		//#region t4 generated members 
		private m_TextLine1: string;

		private m_TextLine2: string;

		private m_TextLine3: string;

		private m_BarcodeData: FP.NavigatorWeb.Common.String8Bit;

		private m_ClearText: FP.NavigatorWeb.Common.String8Bit;

		//#endregion

		//#region t4 generated properties 
		/// <summary>
        /// Gets or sets the TextLine1.
		/// Description: BZL Description Line1
        /// </summary>
        /// <value>The TextLine1.</value>
		get TextLine1(): string { return this.m_TextLine1; }
		set TextLine1(value: string) { this.m_TextLine1 = value; }

		/// <summary>
        /// Gets or sets the TextLine2.
		/// Description: BZL Description Line2
        /// </summary>
        /// <value>The TextLine2.</value>
		get TextLine2(): string { return this.m_TextLine2; }
		set TextLine2(value: string) { this.m_TextLine2 = value; }

		/// <summary>
        /// Gets or sets the TextLine3.
		/// Description: BZL Description Line3
        /// </summary>
        /// <value>The TextLine3.</value>
		get TextLine3(): string { return this.m_TextLine3; }
		set TextLine3(value: string) { this.m_TextLine3 = value; }

		/// <summary>
        /// Gets or sets the BarcodeData.
		/// Description: Content of the 1D Barcode
        /// </summary>
        /// <value>The BarcodeData.</value>
		get BarcodeData(): FP.NavigatorWeb.Common.String8Bit { return this.m_BarcodeData; }
		set BarcodeData(value: FP.NavigatorWeb.Common.String8Bit) { this.m_BarcodeData = value; }

		/// <summary>
        /// Gets or sets the ClearText.
		/// Description: Clear text string of 1D Barcode
        /// </summary>
        /// <value>The ClearText.</value>
		get ClearText(): FP.NavigatorWeb.Common.String8Bit { return this.m_ClearText; }
		set ClearText(value: FP.NavigatorWeb.Common.String8Bit) { this.m_ClearText = value; }

		//#endregion
	}
}

// END: Significant code